### ISSUE TITLE
Build 'Request CRL Items from your Library' workflow

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#10]
Working user story for this workflow:

“As a [persona], I [want to], [so that].”

_As a law librarian (researcher/patron) once I find the specific 20th century Brazilian journal that my students need in the CRL catalog (discovered resource), and that I've verified in not online, I want to borrow it so that my students can access the material locally._

_As a frequent patron of CRL materials I want to learn what my ongoing borrowing options are for accessing materials locally for my research._

_As a law librarian (researcher/patron) once I find the specific 20th century Brazilian journal that my students need in the CRL catalog (discovered resource) I want to see if there's an online version that I can access so that I can reference the materials immediately._ (may related to other issues and workflows, but something we should keep in mind).

Current notes:

> Relates to ILL
> 
> Not necessarily powered by VuFind
> 
> In current catalog, currently generated from a script.
> 
> For every member name, there is a link 
> 
> Could be redesigned
> 
> Call number should be somehow preserved - better for phase 2
> 
> Embed on holdings tab.
> Or create a link to info page.

**Comment by AndyElliottCRL** [comment]
zipped a file with function fill_CRL_member_ILL_form_link_list, has var member_names_and_links, array of objects: 
- **value**: link ILL for the CRL member
- **class**: no need to port over to VuFind
- **text**: name of the CRL member

[fill_CRL_member_ILL_form_link_list.zip](https://github.com/Center-for-Research-Libraries/vufind/files/8466110/fill_CRL_member_ILL_form_link_list.zip)

**Comment by ryan-jacobs** [comment]
Relates to #82 and #64

Also needs input from subject matter experts on request workflows (what data/text/ids do patrons ultimately base their requests on). Teeaye and Marie may have the best knowledge here.

**Comment by AndyElliottCRL** [comment]
To recreate the existing catalog experience, [there is a CRL page on the main site ](http://www.crl.edu/services/borrowing/)
and a similar page in [VuFind](http://ec2-34-234-238-223.compute-1.amazonaws.com/vufind/Content/borrowing).

In the old catalog, every "Borrow from CRL" type link is all going to http://www.crl.edu/services/borrowing/, which is the catch-all page for all such questions.

I suggest http://www.crl.edu/services/borrowing/ for the link in the VuFind header.
![image](https://user-images.githubusercontent.com/2806756/167457047-c60d3610-dba1-4969-a91e-2b6a217fcdd2.png)

**Comment by ryan-jacobs** [comment]
Another note that was shared by Subject Matter folks is that there are cases where we don't have holdings to show but we do have the materials, and could fulfill borrowing requests. I think this means that we also need to add some fallback text to the holdings tab (for non-online cases).

**Comment by ryan-jacobs** [comment]
Moving some of the missing text work into a follow-up: #109
