### ISSUE TITLE
Style language switching component

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#11]
Plan to only support English/French for now.

[Vufind localization documentation:
](https://vufind.org/wiki/development:architecture:localization)
> VuFind supports multiple languages in its user interface through two main mechanisms.
> 
> Translate Function
> VuFind uses Laminas' translation mechanism. The translator object is registered in the service manager under the standard 'Laminas\Mvc\I18n\Translator' key.
> 
> Notes:
> 
> If you attempt to translate a string that is not found in a language map, the original string will be displayed untranslated.
> Many of the translated strings in the language files are simply chunks of English text. However, more recent additions are represented as shorter tokens (i.e. “adv_search_filters”). The token approach is often preferable since it allows for more concise map files and reduces the chances of conflicts where the same text has multiple meanings.
> Starting with VuFind 2.4, a convenient [TranslatorAwareTrait](https://github.com/vufind-org/vufind/blob/dev/module/VuFind/src/VuFind/I18n/Translator/TranslatorAwareTrait.php) has been added which adds VuFind's standard translation capabilities to any object. Use it in combination with the [TranslatorAwareInterface](https://github.com/vufind-org/vufind/blob/dev/module/VuFind/src/VuFind/I18n/Translator/TranslatorAwareInterface.php) to have the translator object automatically injected.

**Comment by KimSarabia** [comment]
@ryan-jacobs Do we want to disable the other languages that isn't French and English for beta?

**Comment by ryan-jacobs** [comment]
> Do we want to disable the other languages that isn't French and English for beta

I don't think so as we a) want our catalog to be as internationally usable as possible and b) already have good string translation available in VuFind for a pretty broad list of languages.

We may want to make a targeted effort to do custom translations of locally-introduced strings (e.g. "Key CRL Collections"), but I think that effort will only be practical against a small sub-set of the languages, at least for the foreseeable future.
