### ISSUE TITLE
Establish beta preview link via banner on current cataog.crl.edu

### ISSUE THREAD

**Issue by ryan-jacobs** [Center-for-Research-Libraries/vufind#112]
Let's consider adding a preview link to the beta directly on the existing Millennium interface.

**Comment by ryan-jacobs** [comment]
For now this should be a static redirect/link effort. More dynamic options could be considered after #14 had had some development effort.

**Comment by AndyElliottCRL** [comment]
From the VuFind catalog, take `div .temporary-notification` and put it in old catalog toplogo.html (will be on every page).  Class definition .temporary-notification in styles.css. 

![Screenshot 2022-05-23 115553](https://user-images.githubusercontent.com/2806756/169870464-9ccc78da-3f83-4957-aa89-888fe06aaafb.png)
