### ISSUE TITLE
Refactor link style

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#114]
## Description

- [ ] Follow up on text underline link feedback that it is not clear it is a link

<img width="378" alt="Screen Shot 2022-05-25 at 12 19 03 PM" src="https://user-images.githubusercontent.com/11491604/170324197-e46efdbd-7f00-4564-8ec2-c16a137713a8.png">

**Comment by ryan-jacobs** [comment]
We may consider leveraging some www styles and concepts here. It looks like we went though a similar analysis there and ended up using underline styles while maintaining branding colors for links. This was a careful process though, as we only wanted the change styles for _inline_ links while allowing other cues (such as menu containers, buttons, etc.) to continue to communicate links elsewhere. So `text-decoration: underline` rules needed to be carefully targeted and/or omitted depending on the parent container(s).

We don't have a full issue for this on www, but this commit may be a useful reference (not for directly repurposed styles, but to reveal some of the thought process): https://github.com/Center-for-Research-Libraries/crl-drupal-www/commit/9680c726ec53733acd7500f7850181751da5509d

Of course, we need to verify that all changes align with accessibility rules and best practices.

**Comment by ryan-jacobs** [comment]
We decided to consolidate to move this into #73

**Comment by ryan-jacobs** [comment]
#73 closed this
