### ISSUE TITLE
Style record page

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#12]
Example: http://catalog.crl.edu/record=b2901763~S5

Proto example: http://ec2-34-234-238-223.compute-1.amazonaws.com/vufind/Record/d6180fd9-f2c3-5b9f-be4a-4e7065f2bb17

**Comment by ryan-jacobs** [comment]
Initially exclude some elements that we are not sure we will include:

- Sidebar
- Similar items tab
- Cover art

**Comment by KimSarabia** [comment]
**To-Style**

- [x] Breadcrumb 

![Screen Shot 2022-04-05 at 6 11 39 PM](https://user-images.githubusercontent.com/11491604/161865835-58edef2c-3daa-408e-ad70-1030de89cb72.png)

- [ ] Similar Items

![Screen Shot 2022-04-05 at 6 12 07 PM](https://user-images.githubusercontent.com/11491604/161865840-8b50c9a4-d439-4512-a91e-5cf6e2407b88.png)

- [ ] Permanent Link

![Screen Shot 2022-04-05 at 6 11 44 PM](https://user-images.githubusercontent.com/11491604/161865877-87062891-6a8d-480b-8ff2-b7361d7f9815.png)

- [ ] Search
<img width="977" alt="Screen Shot 2022-04-06 at 1 29 45 PM" src="https://user-images.githubusercontent.com/11491604/162043901-241c10e1-b0b2-429a-8296-5ed1c2df8e76.png">
