### ISSUE TITLE
Style 'Saved Items' component and modal

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#13]
## Description

The export record functionality in the old catalog is replaced in the Saved Item tab on My Account if you check on the item and export it. 

This ticket will be merged in overall #28 My Account user page that addresses all components in My Account section

**Comment by KimSarabia** [comment]
Save this for beta sprint

**Comment by ryan-jacobs** [comment]
I think that most of this is already handled in simple modal screens from the user account page. We need to confirm, but it's possible that minimal work is needed here.

**Comment by KimSarabia** [comment]
Merged this with #28
