### ISSUE TITLE
Add and document apache rewrite rules to support legacy redirects

### ISSUE THREAD

**Issue by ryan-jacobs** [Center-for-Research-Libraries/vufind#132]
As part of our overall strategy to redirect old URLs to the appropriate locations in VuFind, we need to finalize and document supporting rewrite rules that will do the needed pattern analysis and redirect as needed.

Relates to #14 and #121

Redirect cases to address are listed below. These are loosely ordered by priority based on know usage patters revealed in Google Analytics before launch (against MilCat) and after launch (looking at live patters on new VuFind site):

- [x] Enforce canonical domain
- [x] Redirect prototype /vufind base path to production root path
- [x] Route legacy permalinks to custom resolver for individual records
- [x] Route legacy URLs for targeted searches:
   - [x] OCLC
   - [x] ISSN
   - [x] Title
   - [x] Author
   - [x] Subject
- [x] Route legacy URLs for general searches. For some reason MilCat uses multiple patters for this:
   - [x] `search=` query string
   - [x] `searcharg=` query string (this partially addresses scope-specific searches)
- [x] Route legacy URLs for scope-specific searches and queries. Sub-cases include:
    - [x] Scope landing pages
    - [x] More complex in-scope search/browse URLs (e.g. filter by scope with a keyword active)

**Comment by ryan-jacobs** [comment]
With the permalink redirect controller in place, we can now leverage some apache rewrite rules to direct traffic to the right places, including the new controller. The rules below handle the following cases (assuming VuFind running at / base path):

Set canonical domain. This ensures requests direct to an IP or AWS-specific domain are directed to canonical catalog.crl.edu

```
  # Canonical rules.
  RewriteCond %{HTTP_HOST} !^catalog\.crl\.edu [NC]
  RewriteRule ^ https://catalog.crl.edu%{REQUEST_URI} [L,R=301]
```

Catch old references to the /vufind base path. We initially hosted the site in /vufind directory and want to catch and properly direct any old pointers there:

```
  # VuFind was initially hosted at a /vufind base path, redirect to root base
  RewriteRule ^/vufind$ / [R=301,NC,L]
  RewriteRule ^/vufind/(.*) /$1 [R=301,NC,L]
```

This is a big one -- re-route any legacy permalinks. This simply redirects the permalink URL pattern to our redirect controller that does the heavy lifting to compute what the final target URL should be for a resource based on an old b-resource identifier. That logic was setup in #121 

```
  # Legacy permanlinks get directed to custom VuFind redirect resolver
  RewriteRule ^/record=(b[0-9]{7}) /redirect/b/$1 [R=301,NC,L]
```

Some incoming links point to resources based in an OCLC number (e.g. DDS2 catalog links), so we need to redirect those to an OCLC search. We also use the "jumpto" parameter to tell VuFind to go straight to the resource page if there is only one search result.

```
  # Legacy OCLC lookups can be rewritten directly
  RewriteCond %{QUERY_STRING} search=([0-9]*) [NC]
  RewriteRule ^/search/o /Search/Results?type=oclc_num&jumpto=1&lookfor=%1 [R=301,NC,L,QSD]
```

General searches (of all other types) can be rewritten to an all-fields search in VuFind. These searches start with `search/[type]` where `[type]` is a single character. For later analysis in Google analytics we all append the original request details onto a new redirect_src_path query param while also maintaining the initial query string.

```
  # Other legacy search cases can be rewritten directly to an AllFields search
  # Note that (/|\z) matches a / OR end-of-line. Also capture all path and query
  # string details for analytics.
  RewriteCond %{QUERY_STRING} search=([^&]*) [NC]
  RewriteRule ^/search/[a-z]{1}(/|\z).* /Search/Results?type=AllFields&lookfor=%1&redirect_src_path=$0 [R=301,NC,L,QSA]
```

Finally we have a catch-all for various incoming links that start with `search/~`. This is a common Legacy pattern that may need some additional analysis. It's used for various sub-searches and even various record pages. For now we direct all of these to a new blank search. It's not ideal but it's better than a 404. 

```
  # Catch misc legacy search patterns that could signal a search result and
  # direct to new search. Also capture all path and query string details for
  # analytics.
  RewriteRule ^/search\~.* /Search/Results?redirect_src_path=$0 [R=301,NC,L,QSA]
```

**Comment by AndyElliottCRL** [comment]
Here's a title search: http://catalog.crl.edu/search/t?SEARCH=_Dictionary_
Looks like the main thing here is the **/search/t**

**Comment by ryan-jacobs** [comment]
I also see that woldcat links to our cat via **both** OCLC **and** ISBN searches, with the ISBN pattern like /search/i... so we should handle that as a special case as well.

**Comment by ryan-jacobs** [comment]
I'm seeing some scope-specific links out there as well. Links pointing to something like: http://catalog.crl.edu/search~S3

**Comment by ryan-jacobs** [comment]
Today I also discovered that some of our topic guide citations link to searches that are tightly bound to a scope. This uses a special Mil URL pattern that we don't yet have a redirect rule in place for. See the last citation in the [Agriculture](https://www.crl.edu/collections/topics/agriculture) guide as an example. This is the link: http://catalog.crl.edu/search~S1/X?SEARCH=d%3A%28agriculture%29&searchscope=1&SORT=D&b=txbk

This is not super common and we have a fallback redirect to at least get folks to the VuFind search page (instead of an error page) in cases like this, but it's not ideal and needs improvement.

**Comment by ryan-jacobs** [comment]
I just learned that the jumpto query param does not behave as I thought. Instead of jumping to a resource when there is _only one search result_ it jumps to the numbered value in the param. So jumpto=1 will jump to result number 1 and jumpto=2 will jump to result number 2. This is not good as it could hide cases where multiple results are available (e.g. multiple results that share the same OCLC).

Thankfully it looks like there is a global setting that will still accomplish what we want -- to jump directly to a result when there is only one available. This can be set via a global config option:

`jump_to_single_search_result = true`

The tradeoff here is that it will be active for all searches, not just the ones we specify with a query string. I think that's alright though, as it remains consistent with the Millennium experience.

I've now set this option in the _instance specific_ config.ini for production.

**Comment by ryan-jacobs** [comment]
Type specific searches can be simplified and more inclusive with a RewriteMap:

```
  # All legacy targeted/type searches can be rewritten directly with a map. Also capture
  # all path and query string details for analytics. Note that (/|\z) matches a / OR
  # end-of-line and is necessary to catpure the COMPLETE source string in $0.
  RewriteMap typemap "txt:/usr/local/vufind/local/httpd-type-map.txt"
  RewriteCond %{QUERY_STRING} search=([^&]+) [NC]
  RewriteRule ^/search/([a-z]{1})(/|\z).* /Search/Results?type=${typemap:${lc:$1}|AllFields}&lookfor=%1&redirect_src_path=$0 [R=301,NC,NE,L,QSA]
```

Then using a httpd-type-map.txt file like:

```
o oclc_num
i ISN
t Title
a Author
d Subject
```

Will cover all 5 targeted search types that overlap between MilCat and VuFind

**Comment by ryan-jacobs** [comment]
Scope-specific searches still need some attention. These can be a bit complex to untangle and could include combinations of search dimensions (e.g. scope + type). It also appears that in-scope searches use different query parameters than homepage searches, specifically switching to a `searcharg=` param instead of `search=`. So for now I've added a rules to capture `searcharg=` cases. This does not yet redirect to a scope-specific facet in VuFind, but it does properly retain the search keywords. 

```
  # Scope-specific searches use a "searcharg" query param instead of "search".
  # These need to be handled with their own rule. Also capture all path and query
  # string details for analytics.
  RewriteCond %{QUERY_STRING} searcharg=([^&]+) [NC]
  RewriteRule ^/search\~.* /Search/Results?type=AllFields&lookfor=%1&redirect_src_path=$0 [R=301,NC,L,QSA]
```

**Comment by ryan-jacobs** [comment]
Scoped redirects requires some thinking as there are several ways that scopes may have been defined in MilCat (query string, url, etc.). While incorporating scope rules I was also able to consider some ways to consolidate rules and further increase some generic pattern coverage. Here's the current full set of rules being evaluated in production:

```
  # Start rewrites
  RewriteEngine On
  # Declare generic lowecase map for use in various RewriteMap rules
  RewriteMap lc int:tolower
  RewriteMap typemap "txt:/usr/local/vufind/local/httpd-type-map.txt"
  RewriteMap scopemap "txt:/usr/local/vufind/local/httpd-scope-map.txt"
  # Canonical rules.
  RewriteCond %{HTTP_HOST} !^catalog\.crl\.edu [NC]
  RewriteRule ^ https://catalog.crl.edu%{REQUEST_URI} [L,R=301]
  # VuFind was initially hosted at a /vufind base path, redirect to root base
  RewriteRule ^/vufind$ / [R=301,NC,L]
  RewriteRule ^/vufind/(.*) /$1 [R=301,NC,L]
  # Legacy permanlinks get directed to custom VuFind redirect resolver
  RewriteRule ^/record=(b[0-9]{7}) /redirect/b/$1 [R=301,NC,L]
  # A legacy scoped AND typed search can have all vars in the query string.
  # Redirect to matching VuFind filters.
  RewriteCond %{QUERY_STRING} searchtype=([a-zA-Z]{1}).*(search|searcharg)=([^&]+).*searchscope=([0-9]{1,2}) [NC]
  RewriteCond %{QUERY_STRING} !redirect_src_path [NC]
  RewriteCond ${scopemap:%4} !=""
  RewriteRule ^/search.* /Search/Results?type=${typemap:${lc:%1}|AllFields}&lookfor=%3&filter[]=crl_scope:${scopemap:%4}&redirect_src_path=$0 [R=301,NC,L,QSA]
  # A variant of the rule above is needed to catch cases where we don't have a
  # scope-to-Key-Collection match or no scope info is passed-in. In this case we
  # drop the Key Collection filter.
  RewriteCond %{QUERY_STRING} searchtype=([a-zA-Z]{1}).*(search|searcharg)=([^&]+) [NC]
  RewriteCond %{QUERY_STRING} !redirect_src_path [NC]
  RewriteRule ^/search.* /Search/Results?type=${typemap:${lc:%1}|AllFields}&lookfor=%3&redirect_src_path=$0 [R=301,NC,L,QSA]
  # A legacy scoped AND typed search can also have the type defined in the URL
  # instead of the query string. Redirect to matching VuFind filters.
  # Note that (/|\z) matches a / OR end-of-line and is necessary to catpure the
  # COMPLETE source string in $0.
  RewriteCond %{QUERY_STRING} (search|searcharg)=([^&]+).*searchscope=([0-9]{1,2}) [NC]
  RewriteCond %{QUERY_STRING} !redirect_src_path [NC]
  RewriteCond ${scopemap:%3} !=""
  RewriteRule ^/search/([a-zA-Z]{1})(/|\z).* /Search/Results?type=${typemap:${lc:$1}|AllFields}&lookfor=%2&filter[]=crl_scope:${scopemap:%3}&redirect_src_path=$0 [R=301,NC,L,QSA]
  # A variant of the rule above is needed to catch cases where we don't have a
  # scope-to-Key-Collection match or no scope info is passed-in. In this case we
  # drop the Key Collection filter.
  RewriteCond %{QUERY_STRING} (search|searcharg)=([^&]+) [NC]
  RewriteCond %{QUERY_STRING} !redirect_src_path [NC]
  RewriteRule ^/search/([a-zA-Z]{1})(/|\z).* /Search/Results?type=${typemap:${lc:$1}|AllFields}&lookfor=%2&redirect_src_path=$0 [R=301,NC,L,QSA]
  # Legacy scope langing pages have the scope in the URL which requires special
  # handling.
  RewriteCond ${scopemap:$1} !=""
  RewriteCond %{QUERY_STRING} !redirect_src_path [NC]
  RewriteRule ^/search~S([0-9]{1,2})(/|\z).* /Search/Results?filter[]=crl_scope:${scopemap:$1}&redirect_src_path=$0 [R=301,NC,L,QSA]
  # Catch misc legacy search patterns not already addressed above that could
  # signal a search result and direct to new search.
  RewriteCond %{QUERY_STRING} !redirect_src_path [NC]
  RewriteRule ^/search\~.* /Search/Results?redirect_miss=1&redirect_src_path=$0 [R=301,NC,L,QSA]
```

**Comment by ryan-jacobs** [comment]
I was recently informed that we may have some encoding errors, specifically for spaces. When using the search box on the main website a keyphrase with spaces in it gets passed to the catalog with the spaces replaced with "%20".

This seems to happen because Drupal URLencodes the spaces from the form submission before redirecting to an old legacy cat URL (/search/Y?SEARCH=*). That redirect is then passed though another redirect (defined in this issue) to get to the right VuFind path. In that second redirect it seems that the "%" in the space-encoded %20 gets double-encoded.

We can disable this double-encoding with the no-encode (NE) flag on any rewrite rules that process search terms.

This results in the slightly updated rules:

```
  # Start rewrites
  RewriteEngine On
  # Declare generic lowecase map for use in various RewriteMap rules
  RewriteMap lc int:tolower
  RewriteMap typemap "txt:/usr/local/vufind/local/httpd-type-map.txt"
  RewriteMap scopemap "txt:/usr/local/vufind/local/httpd-scope-map.txt"
  # Canonical rules.
  RewriteCond %{HTTP_HOST} !^catalog\.crl\.edu [NC]
  RewriteRule ^ https://catalog.crl.edu%{REQUEST_URI} [L,R=301]
  # VuFind was initially hosted at a /vufind base path, redirect to root base
  RewriteRule ^/vufind$ / [R=301,NC,L]
  RewriteRule ^/vufind/(.*) /$1 [R=301,NC,L]
  # Legacy permanlinks get directed to custom VuFind redirect resolver
  RewriteRule ^/record=(b[0-9]{7}) /redirect/b/$1 [R=301,NC,L]
  # A legacy scoped AND typed search can have all vars in the query string.
  # Redirect to matching VuFind filters.
  RewriteCond %{QUERY_STRING} searchtype=([a-zA-Z]{1}).*(search|searcharg)=([^&]+).*searchscope=([0-9]{1,2}) [NC]
  RewriteCond %{QUERY_STRING} !redirect_src_path [NC]
  RewriteCond ${scopemap:%4} !=""
  RewriteRule ^/search.* /Search/Results?type=${typemap:${lc:%1}|AllFields}&lookfor=%3&filter[]=crl_scope:${scopemap:%4}&redirect_src_path=$0 [R=301,NC,NE,L,QSA]
  # A variant of the rule above is needed to catch cases where we don't have a
  # scope-to-Key-Collection match or no scope info is passed-in. In this case we
  # drop the Key Collection filter.
  RewriteCond %{QUERY_STRING} searchtype=([a-zA-Z]{1}).*(search|searcharg)=([^&]+) [NC]
  RewriteCond %{QUERY_STRING} !redirect_src_path [NC]
  RewriteRule ^/search.* /Search/Results?type=${typemap:${lc:%1}|AllFields}&lookfor=%3&redirect_src_path=$0 [R=301,NC,NE,L,QSA]
  # A legacy scoped AND typed search can also have the type defined in the URL
  # instead of the query string. Redirect to matching VuFind filters.
  # Note that (/|\z) matches a / OR end-of-line and is necessary to catpure the
  # COMPLETE source string in $0.
  RewriteCond %{QUERY_STRING} (search|searcharg)=([^&]+).*searchscope=([0-9]{1,2}) [NC]
  RewriteCond %{QUERY_STRING} !redirect_src_path [NC]
  RewriteCond ${scopemap:%3} !=""
  RewriteRule ^/search/([a-zA-Z]{1})(/|\z).* /Search/Results?type=${typemap:${lc:$1}|AllFields}&lookfor=%2&filter[]=crl_scope:${scopemap:%3}&redirect_src_path=$0 [R=301,NC,NE,L,QSA]
  # A variant of the rule above is needed to catch cases where we don't have a
  # scope-to-Key-Collection match or no scope info is passed-in. In this case we
  # drop the Key Collection filter.
  RewriteCond %{QUERY_STRING} (search|searcharg)=([^&]+) [NC]
  RewriteCond %{QUERY_STRING} !redirect_src_path [NC]
  RewriteRule ^/search/([a-zA-Z]{1})(/|\z).* /Search/Results?type=${typemap:${lc:$1}|AllFields}&lookfor=%2&redirect_src_path=$0 [R=301,NC,NE,L,QSA]
  # Legacy scope langing pages have the scope in the URL which requires special
  # handling.
  RewriteCond ${scopemap:$1} !=""
  RewriteCond %{QUERY_STRING} !redirect_src_path [NC]
  RewriteRule ^/search~S([0-9]{1,2})(/|\z).* /Search/Results?filter[]=crl_scope:${scopemap:$1}&redirect_src_path=$0 [R=301,NC,L,QSA]
  # Catch misc legacy search patterns not already addressed above that could
  # signal a search result and direct to new search.
  RewriteCond %{QUERY_STRING} !redirect_src_path [NC]
  RewriteRule ^/search\~.* /Search/Results?redirect_miss=1&redirect_src_path=$0 [R=301,NC,L,QSA]
```

**Comment by ryan-jacobs** [comment]
These rules have been tested with success in production. Closing.
