### ISSUE TITLE
Mil usage pattern analysis

### ISSUE THREAD

**Issue by ryan-jacobs** [Center-for-Research-Libraries/vufind#19]
This is a planning issue.

We need clear pictures about existing nav patterns to inform some feature decisions.

Examples include:

- Scope-based usage (% across scopes)
- Drop-down filter usage (Author, ISSN, OCLC, etc.)

**Comment by ryan-jacobs** [comment]
I have started a spreadsheet to track some usage patters to support this effort. As it's an Office365 doc link I'll share it via other channels in case we open-up the issue queues later as part of a public repo.

**Comment by ryan-jacobs** [comment]
Some base analysis is shaping up at: https://crldomain-my.sharepoint.com/:x:/g/personal/rjacobs_crl_edu/EQojH7fs965EgcLEzuNtQO0BrO95mnqK-2uZs3_Km3zKfA?e=qntqwb

**Comment by AndyElliottCRL** [comment]
Added to sheet a few patterns from the smaller searches under the Serials and Dissertations scopes. These use searchtype=Y, d, a and are included in previous rows compiled by @ryan-jacobs . 
We did not build anything new into Millenium WebPAC back end to create those special searches; we just added the forms and search widgets to the page and the searches are handled natively.

**Comment by ryan-jacobs** [comment]
Thanks @AndyElliottCRL. Were you thinking that some scopes may use the search search "type" options in unique ways that we may want to get data for? I was wondering myself if it would be useful to see a breakdown of the "Searches by Type" report for some targeted scopes. My assumption is that the patters will be similar across scopes as within individual scopes, but I could be wrong about that.

**Comment by AndyElliottCRL** [comment]
> Were you thinking that some scopes may use the search search "type" options 
> in unique ways that we may want to get data for?

Not really, just that CRL did not use those options in a unique way. From looking at the input forms, I think the existing sheet captures all the patterns we have set up for searches.  

Looking into searches by type per scope could be useful or interesting but may not open up anything brand new. 
Logged visits with "export" in the url should give us counts of how often people email saved lists to themselves/make a print view. This minor point is the only general area I have not seen a number for.

**Comment by ryan-jacobs** [comment]
So it looks like the current stats we have summarized in our spreadsheet are the right starting point and we can leverage these as needed for future decision making. Some more targeted needs may certainly come up, but I'll go ahead and close this.
