### ISSUE TITLE
Add option to do in-place re-harvest

### ISSUE THREAD

**Issue by ryan-jacobs** [Center-for-Research-Libraries/vufind#20]
The currently harvest options, as supported by .sh scripts, are to an incremental harvest or to do a full re-harvest. That latter also appears to totally reset and rebuild the index so there is a period of days where records are missing. It would be nice to be able to completely re-index without destroying the existing index (i.e. and in place re-index).

This could be useful to do after large bulk updates/upserts when we want to have a way to trigger/monitor the related harvest directly but still want to preserve the existing records for public access.

**Comment by ryan-jacobs** [comment]
A quick experiment has revealed that resetting the date in local/harvest/crl/last_harvest.txt (to something well in the past) and running incremental.sh seems to do an in-place re-harvest of all records. We should still confirm if there are any gotchas with this, especially in a production environment.

**Comment by mmabrahamson** [comment]
You're correct, @ryan-jacobs, that setting last_harvest.txt to something well in the past will cause the harvest function in VuFind to effectively pull the entire catalog again.  This is actually essential to do with a full import.  To be honest, I haven't done this with incremental updates.  My biggest concern would be if duplicates begin to appear.  Theoretically, Solr should be able to eliminate these during the optimize process, however I would test it to be sure.

**Comment by ryan-jacobs** [comment]
It looks like no real action is needed here. I'm just going to update the readme to capture some notes about this in a central place.
