### ISSUE TITLE
Style user account page

### ISSUE THREAD

**Issue by ryan-jacobs** [Center-for-Research-Libraries/vufind#28]
The team decided to allow some VuFind features that leverage authentication, specifically personalziation features like saved searches and saved lists. See the workspace notes for more about this decision:

https://workspace.crl.edu/display/CISTF/Authentication+and+Personalization+Features

As we will be enabling a subset of personalization features we also need to verify the styling of the user account homepage where their saved content is listed:

/vufind/MyResearch/Home

**Comment by ryan-jacobs** [comment]
We also need to consider removing some of the menu items on the my account page that we will not be using in phase 1 (Checked out Items, Holds and Recalls, Fines). These do not appear to be individually configurable and are instead based on low-level code checks in the FOLIO driver. This means the best way to remove these may be to modify the template directly in `theme/templates/myresearch/menu.phtml`

**Comment by KimSarabia** [comment]
To-Do:
All Modals (Including export saved record #13 )
All filters
