### ISSUE TITLE
make non-roman data more prominent

### ISSUE THREAD

**Issue by AndyElliottCRL** [Center-for-Research-Libraries/vufind#33]
Not directly related to #31 where there is no non-roman data. 

In a previous VF build there were Russian title fields, but they were much smaller than the romanized version, I looked at several records before I even saw it.
This issue is that the original non-roman data should be at least as large and readable as the fake version.

**Comment by ryan-jacobs** [comment]
@AndyElliottCRL can you link to a specific example in the prototype so we can see what's happening?

I'm also adding the project link here so we can track this.

**Comment by AndyElliottCRL** [comment]
WebPAC Millenium: http://catalog.crl.edu/record=b2695326~S3
VuFind: http://ec2-34-234-238-223.compute-1.amazonaws.com/vufind/Record/ab53d389-3c1d-5c13-b2c7-b35f067e2f60
![ex1](https://user-images.githubusercontent.com/2806756/161862646-f6941f21-f507-490e-ab37-4a09d6f7a2f4.png)

**Comment by ryan-jacobs** [comment]
Thanks for the example @AndyElliottCRL . This is actually a case where VuFind is pulling from the 880 at display time (as discussed in #31). This text is scaled the same as other general body text which I think is consistent with other CRL treatments, such as DDSNext. See [this example](http://ddsnext.crl.edu/titles/14618):

<img width="1022" alt="Screen Shot 2022-04-06 at 1 51 14 PM" src="https://user-images.githubusercontent.com/1338410/162047581-b843f957-b8d9-46c2-a13a-7d9eed356bef.png">

There we also use the same styling as other body text. I think the idea is to ensure that we only only have one version of the title text using an h1 style. Do you think this is inappropriate or inconsistent with user expectations?

**Comment by AndyElliottCRL** [comment]
I think the original title should be most prominent, that the Abai Geser DDS ex. has the original title way too small. 

All these indexed fields should not imho be treated as simple body text and we should emulate the CRL WebPAC catalog display here.  The CRL catalog is giving them equal prominence which is appropriate; making either one so small is bad for one or the other user group.

**Comment by KimSarabia** [comment]
Potential To-Do:
See if this will work: https://www.w3.org/International/questions/qa-css-lang

**Comment by AndyElliottCRL** [comment]
Sample title from above, in Worldcat http://www.worldcat.org/oclc/417851236

![issue33worldcat](https://user-images.githubusercontent.com/2806756/162789961-633757c5-fa58-4b50-a27b-23c3ba8e27b5.png)

**Comment by KimSarabia** [comment]
**To-Do:**
Follow WorldCat semantics and CSS
