### ISSUE TITLE
Alpha Accessibility and Performance Test through Lighthouse

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#37]
## Description

Run accessibility test on Lighthouse

**Comment by ryan-jacobs** [comment]
I suspect that link styles may need attention as they blend into surrounding text a bit currently.

**Comment by KimSarabia** [comment]
<img width="823" alt="Screen Shot 2022-04-22 at 9 07 15 AM" src="https://user-images.githubusercontent.com/11491604/164730938-88a2790c-fe95-4ec8-872c-1777dcbf1ae9.png">

**Comment by KimSarabia** [comment]
[Report](https://crldomain-my.sharepoint.com/:b:/g/personal/ksarabia_crl_edu/EXJ6OSqhN3xIlpmghVf7Je0Bq6JjqFml8UKQurVa3CooMQ?e=bfhr1z)
