### ISSUE TITLE
Change site title

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#44]
## Description

Change site title

**Comment by ryan-jacobs** [comment]
Perhaps we can also use this issue to discuss the addition of a site title visually to the header. The term "Online Catalog" should probably appear in the header area to differentiate this site from other CRL properties at a glance.

A couple of ides that come to mind

- Change logo to brandmark and then use the area to the right of it for title text - blue circle below
- Place title text inside the blue menubar area (though this might conflict with other responsive rules) - red circle below

<img width="795" alt="Screen Shot 2022-04-13 at 9 55 20 AM" src="https://user-images.githubusercontent.com/1338410/163209323-028b285f-c664-47f3-9197-36de7eace89d.png">

**Comment by ryan-jacobs** [comment]
"Online catalog" text display considerations moved to #55
