### ISSUE TITLE
Create on footer content checklist 

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#45]
## Description

Consult with relevant stakeholders on footer content and finalize list of required content

> What elements to keep in footer. The main website elements are definitely the right starting point here, I'm just not sure about the social links and sub-site links. This may be one aspect to get some Comm feedback on eventually.

**Comment by ryan-jacobs** [comment]
Adding to project so we don't loose track. Thanks for opening this.

**Comment by KimSarabia** [comment]
Interlibrary Loan link text will change and should match Borrowing from CRL link in header

**Comment by KimSarabia** [comment]
We don't need:

Remove:
Ask a Librarian
FAQs

Remove:
Explore Channels
Course Reserves
New Items

See if it is a config option?


---

Remove other website links
Replace with 
1. VuFind and Folio note (use uChicago note)
2. Accessibility
3. Privacy Policy

**Comment by KimSarabia** [comment]
Update: Drop the FIND MORE column altogether and move Browse Catalog to first column
