### ISSUE TITLE
Add borders to records page components

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#46]
## Description

> Possibly styling to break-up some parts of the record page (e.g. should we visually separate the body area from tabbed-sections or do any other container styling here? (From #18 )

**Comment by KimSarabia** [comment]
@ryan-jacobs I was trying to borrow elements from Google Books book page for the records page. I want to add more borders, but it might be good to finalize what content we will keep and get rid of before moving forward, and if there is any desire for any layout changes for alpha.
<img width="1110" alt="Screen Shot 2022-04-08 at 2 25 56 PM" src="https://user-images.githubusercontent.com/11491604/162510941-2a852b2a-ef0f-4e42-b8fa-4ca7e75371f9.png">

**Comment by ryan-jacobs** [comment]
> it might be good to finalize what content we will keep and get rid of before moving forward

Yes, that's a good point. This is one important pending area for input from the Subject Matter experts ahead of the Alpha release. I think it's safe to say that we will maintain a separation between the main fields area and the tabbed elements below it, but beyond that things are a little in flux.

Google books is an interesting reference. At some point it might be good for me to learn a bit more about how material design principles and language play out at the _layout_ level, as I think that's what we are talking about in this issue and maybe also a bit in #5.

**Comment by ryan-jacobs** [comment]
Marie and Ryan are planning to discuss some details that relate to this on Thurs. @KimSarabia I will make sure you are invited.

**Comment by ryan-jacobs** [comment]
After talking to Kim we decided to avoid region styling for the alpha version and focus primarily on material design card styling for components within regions (i.e. no visual boundaries between regions initially).
