### ISSUE TITLE
Fix search dropdown bug

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#57]
![Screen Shot 2022-04-13 at 2 53 34 PM](https://user-images.githubusercontent.com/11491604/163259636-dfa8cf9b-c887-4481-b355-e2727879fe0c.png)

**Comment by ryan-jacobs** [comment]
Does this refer to the way the dropdown is not properly anchored to the form field? If so, is it possible that this is a browser-specific bug?

**Comment by KimSarabia** [comment]
> Does this refer to the way the dropdown is not properly anchored to the form field? If so, is it possible that this is a browser-specific bug?

Yes, good catch! I've narrowed it down to Chrome

**Comment by KimSarabia** [comment]
Putting this on hold as this requires a bit more research and is a blocker

**Comment by AndyElliottCRL** [comment]
Not seen in Brave or Firefox 20220601.

**Comment by KimSarabia** [comment]
Also checked on Safari iOS, Safari macOS and Chrome in macOS. The bug no longer can be replicated. Closing for now.
