### ISSUE TITLE
Add support for Related Items and Continues

### ISSUE THREAD

**Issue by ryan-jacobs** [Center-for-Research-Libraries/vufind#59]
It does not seem like VuFind natively handles 780 and 785 fields to display related items and continues. In Millennium these would be displayed with links to a canned search (typically using a title-based string search, or possibly a direct OCLC search depending on available sub-fields) so that the user could navigate between related titles.

The Record Version feature of VuFind may help here, but it is based on completely different indexing tricks (see https://vufind.org/wiki/configuration:record_versions) and not using info directly from the individual record 780 and 785 fields. Our patrons will greatly value the ability to use the 780 and 785 data that's directly in the record.

**Comment by ryan-jacobs** [comment]
UofC seems to have implemented or enabled some form of this functionality, as seen in this example:

https://catalog.lib.uchicago.edu/vufind/Record/1631388

**Comment by ryan-jacobs** [comment]
It actually looks like there is some native support, at least for 785s. To see this in the output one must currently look inside the "Description" tab. Here's an example:

http://ec2-34-234-238-223.compute-1.amazonaws.com/vufind/Record/beb75b02-5300-558a-bac3-45a41d98341f#description

There is no active linking as far as I can see, but it's good to see something to build off of here.

**Comment by ryan-jacobs** [comment]
Looking further, it seems like active linking via 780/785 IDs is natively available (@AndyElliottCRL , @mmabrahamson )! It's not well documented and is still dependent on the addition of a new custom field to the record display, but most of the heavy business logic needed is there. It's buried, but it's there.

See:

- Related config: https://github.com/Center-for-Research-Libraries/vufind/blob/crl-dev/local/config/vufind/config_common.ini#L1784
- Getter that can be the basis of a "Record Links" field: https://github.com/Center-for-Research-Libraries/vufind/blob/crl-dev/module/VuFind/src/VuFind/RecordDriver/Feature/MarcAdvancedTrait.php#L581

This seems to refrence 780s and 785 and can build internal links based on id, oclc, dlc, isbn, issn, and title values present in subfield "w"

**Comment by ryan-jacobs** [comment]
Note to team (once there are implementation resources to put on this), I think the following spec addition would cover the needed field definition for this:

```
        $spec->setTemplateLine(
            'Related Items', 'getAllRecordLinks', 'data-allRecordLinks.phtml'
        ); 
```

But it will only work once the relevant details are uncommented from the `[Record]` section of config.ini.

**Comment by AndyElliottCRL** [comment]
Labeling of "related" item tags from Millenium. 
marc_field and indicators 
dot means for all indicator values in that position 
blank indicator is different from dot, means only null or space
brackets mean only specific values in that indicator position

related title labels
730. 	Related title
730.2	Contains related title // any first indicator with second ind. 2
	Related Work // default 730 label
740. 	Related title
740.2 Contains title

776	Additional physical format

780.[23]	Supersedes # first indicator blank, second ind. 2, or 3
780.[56]	Absorbed
780.7	Separated from
	Continues // default 780 label
785.1	Continued in Part By
785.[23]	Superseded By
785.[45]	Absorbed By
785.6	Related in Split
785.7	Related in Merge
785.8	Changed Back To
	Continued By // default 785 label

**Comment by AndyElliottCRL** [comment]
Labels have their own issue now: https://github.com/Center-for-Research-Libraries/vufind/issues/92, with better formatting and details for title and note field labels there too.

**Comment by ryan-jacobs** [comment]
I think this means we are in good shape on this issue then, and can move other work to follow-up as #92. Thanks @AndyElliottCRL
