### ISSUE TITLE
Style holdings component

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#64]
## Description

Wait until the holdings data is rendered

**Comment by ryan-jacobs** [comment]
Here are some examples that demonstrate different kinds of holdings data:

With holdings notes and multiple items: http://ec2-34-234-238-223.compute-1.amazonaws.com/vufind/Record/13fb4657-c103-566a-8b4c-6b7c474a3e2c

With holdings notes and item notes: http://ec2-34-234-238-223.compute-1.amazonaws.com/vufind/Record/0b964599-474e-52ad-80ca-43e0af863b67

Simple single item monograph without volume/description info in item: http://ec2-34-234-238-223.compute-1.amazonaws.com/vufind/Record/0035fd85-9b61-5893-9b8a-8a1a07738b2c
