### ISSUE TITLE
Miscellaneous styles [placeholder ticket]

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#73]
## Description

This is an evolving to-do list of small style updates that I find as we work on other tickets

- [x] search results list item `.badge` style -> consider turning it into button style, but need to check accessibility

![Screen Shot 2022-04-20 at 4 49 05 PM](https://user-images.githubusercontent.com/11491604/164329229-630091ba-22ba-4d1b-ba27-53706ca90514.png)

- [x] Sidebar number count -> consider darkening it and matching it to the text

![Screen Shot 2022-04-20 at 4 49 09 PM](https://user-images.githubusercontent.com/11491604/164329149-f472b086-a0ca-45da-8b91-cdf0dca31068.png)

Mobile overcrowding
<img width="332" alt="Screen Shot 2022-04-22 at 9 02 37 AM" src="https://user-images.githubusercontent.com/11491604/164730119-d39212ae-5d88-4c9a-8829-42fd49f0c8d3.png">

- [x] Address Andy's comment

- [x] Address the green button/label issue

<img width="378" alt="Screen Shot 2022-05-25 at 12 19 03 PM" src="https://user-images.githubusercontent.com/11491604/170324197-e46efdbd-7f00-4564-8ec2-c16a137713a8.png">

**Comment by KimSarabia** [comment]
Add #114 to this ticket's to-do's
---

> ## Description

- [ ] Follow up on text underline link feedback that it is not clear it is a link

<img width="378" alt="Screen Shot 2022-05-25 at 12 19 03 PM" src="https://user-images.githubusercontent.com/11491604/170324197-e46efdbd-7f00-4564-8ec2-c16a137713a8.png">

---
> [ryan-jacobs](https://github.com/ryan-jacobs) commented [13 days ago](https://github.com/Center-for-Research-Libraries/vufind/issues/114#issuecomment-1137817046) • 
We may consider leveraging some www styles and concepts here. It looks like we went though a similar analysis there and ended up using underline styles while maintaining branding colors for links. This was a careful process though, as we only wanted the change styles for inline links while allowing other cues (such as menu containers, buttons, etc.) to continue to communicate links elsewhere. So text-decoration: underline rules needed to be carefully targeted and/or omitted depending on the parent container(s).

> We don't have a full issue for this on www, but this commit may be a useful reference (not for directly repurposed styles, but to reveal some of the thought process): https://github.com/Center-for-Research-Libraries/crl-drupal-www/commit/9680c726ec53733acd7500f7850181751da5509d

> Of course, we need to verify that all changes align with accessibility rules and best practices.

**Comment by ryan-jacobs** [comment]
@KimSarabia , it looks like the format (e.g. "Online Access") badges are still getting hidden, though I see this was closed. Was that part moved to another issue?
