### ISSUE TITLE
Research and update documentation on how to update translation strings

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#80]
## Description
Document language string policy
Figure out how to create local version of languages .ini files
See [conversation](https://github.com/Center-for-Research-Libraries/vufind/pull/71#discussion_r854601924) #5

Dependency for: https://github.com/Center-for-Research-Libraries/vufind/issues/45

**Comment by KimSarabia** [comment]
Will try this:
> Customizing Language Files
If you need to customize the language files residing in VUFIND_HOME/languages but do not want to commit this customization to the dev branch, you only need to create a languages folder in your local folder (or any folder that is configured as your VUFIND_LOCAL_DIR). Any language file in your VUFIND_LOCAL_DIR/languages folder will be merged with its corresponding language file in VUFIND_HOME/languages (implicit inheritance).

> Starting with VuFind 2.5, you can also put a languages directory inside a [theme](https://vufind.org/wiki/development:architecture:user_interface) folder to apply custom translations to that specific theme. This can be useful, for example, to use shorter strings in a mobile interface than a desktop version.

Source: https://vufind.org/wiki/development:architecture:localization

**Comment by ryan-jacobs** [comment]
Implicit inheritance as defined in the docs does seem to work. The trick is that you have to clear all caches before the changes take effect.
