### ISSUE TITLE
Finalize strategy on css compilation

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#81]
## Description

- [ ] Recompile the css on dev?
- [ ] Uncommit the compiled css?
Instance specific compile?

- [ ] Update theme.config settings to compile css on the dev instance?
- [ ] Consider how often vufind would compile and how it affects speed

**Comment by ryan-jacobs** [comment]
A couple quick comments:

- Multiline compiled output will be more friendly to merges (avoid merge conflicts) ... (default for lessc but may be param for grunt)
- Map file are very useful to generate at commit time (default for lessc but may be param for grunt)

**Comment by ryan-jacobs** [comment]
Also, regarding the idea to use server-side compilation (and gitignore compiled css outputs):

I think this could work, and does seem to be a strategy that some folks use. My only worry would be related to the timing of the compilation process. If compilation is auto-triggered on every single page load that would be very handy for dev environments but not performant for our prototype or production environments. If we explore this option we need to better understand how the theme framework deals with this.

See also https://vufind.org/wiki/development:architecture:less, specifically the "Active Compilation" section.

**Comment by ryan-jacobs** [comment]
Note that #83 is related, but I don't think the resolution there will impact final decisions about the best way to handle compilation going forward.

**Comment by ryan-jacobs** [comment]
Note also that `grunt lessdev` (as opposed to `grunt less`) seems to produce multiline compiled output and embed map details in the output. The catch is that it does this for **all** themes (not just CRL). Not a big issue I suppose. The only consequence I could see would be a potential merge conflict during a future core vufind update, but that's manageable. Anyway, this could be a workable solution. @KimSarabia, you can probably best assess the right path forward here.

**Comment by KimSarabia** [comment]
I think I will just keep `grunt less` for now. It compiles properly and does not seem to cause speed/performance issues.
